#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Plant Area Density (PAD) Calculation from Normalized Return Density (NRD)

This script calculates Plant Area Density (PAD) from Normalized Return Density (NRD) values
using the Beer-Lambert law approach. PAD is a crucial vegetation structure metric that 
measures the distribution of plant material in 3D space (m²/m³).

Dependencies:
------------
Required Python packages:
- numpy: Array operations and mathematical functions
- pandas: Data frame handling and CSV processing
- gdal: Geospatial data processing and raster creation
- matplotlib: Visualization and plotting
- logging: Progress tracking and error reporting

System Requirements:
------------------
- Python 3.7 or higher
- GDAL binaries installed and accessible
- Sufficient disk space for raster outputs
- Memory: At least 4GB recommended for large datasets

Input Requirements:
-----------------
- NRD CSV files from NRD_calculation.py
- NRD raster files in GeoTIFF format
- Consistent height binning across inputs
- Valid georeference information

The calculation follows the methodology:
PAD(z) = -ln(1 - NRD(z))/(κ · Δz)

Where:
- NRD(z): Normalized Return Density at height bin z
- κ: Extinction coefficient (species-specific parameter)
- Δz: Height bin size in meters

This script uses true NRD rasters generated by NRD_calculation.py to calculate PAD values.
Each pixel in these rasters contains the actual NRD value (0-1 range) calculated as:
NRD = (points in current bin) / (points in current bin and all bins BELOW it)

The Beer-Lambert law is applied directly to these values, providing a scientifically 
rigorous and mathematically consistent calculation of PAD.

Output Products:
--------------
1. CSV Files:
   - PAD values for each height bin
   - Processing parameters and metadata
   
2. Raster Files:
   - GeoTIFF format with PAD values
   - One file per height bin
   - Combined VRT for 3D visualization
   
3. Visualizations:
   - Multi-panel plots of NRD, transmittance, and PAD
   - Height profiles of vegetation structure
   
4. Documentation:
   - README file with processing details
   - Metadata in raster files
   - Processing logs

Quality Control:
--------------
- Numerical stability checks
- Bounded PAD values (0-10 m²/m³)
- NoData handling
- Error logging and reporting

Author: Forest Fire Model Development Team
Date: 2023
"""

# -------------------------------------------------------------------------
# GLOSSARY AND THEORETICAL BACKGROUND
# -------------------------------------------------------------------------
"""
GLOSSARY OF TERMS AND CONCEPTS
=============================

FUNDAMENTAL CONCEPTS
------------------
1. Beer-Lambert Law:
   - Physical law describing light attenuation through a medium
   - Original form: I = I₀ e^(-κL)
   - I = transmitted intensity
   - I₀ = initial intensity
   - κ = extinction coefficient
   - L = path length

2. Application to Vegetation:
   - Describes laser pulse penetration through canopy
   - Modified for discrete LiDAR returns
   - Accounts for canopy structure and density

VEGETATION METRICS
----------------
1. Plant Area Density (PAD):
   - Definition: Vegetation material per unit volume
   - Units: m²/m³
   - Range: Typically 0-10 m²/m³
   - Calculation: -ln(1 - NRD)/(κ · Δz)
   - Physical meaning: One-sided plant area per unit volume

2. Normalized Return Density (NRD):
   - Definition: Proportion of returns at height z relative to all below
   - Range: 0-1 (proportion)
   - Calculation: points_in_bin / (points_in_bin + points_below)
   - Represents: Relative vegetation density at each height

3. Transmittance (Gap Fraction):
   - Definition: Proportion of light penetrating canopy
   - Range: 0-1
   - Calculation: 1 - NRD
   - Represents: Canopy openness

PARAMETERS AND COEFFICIENTS
-------------------------
1. Extinction Coefficient (κ):
   - Species-specific parameter
   - Typical ranges:
     * Coniferous: 0.5-0.7
     * Deciduous: 0.4-0.6
     * Mixed: ~0.5
     * Shrubland: 0.3-0.5
   - Affects: PAD magnitude

2. Height Bin Size (Δz):
   - Vertical resolution of analysis
   - Typical: 2m
   - Affects: PAD resolution and magnitude
   - Trade-off: Resolution vs. point density

QUALITY CONTROL PARAMETERS
------------------------
1. MIN_PAD_VALUE:
   - Minimum allowable PAD
   - Prevents negative values
   - Typically 0.0 m²/m³

2. MAX_PAD_VALUE:
   - Maximum allowable PAD
   - Prevents unrealistic values
   - Typically 10.0 m²/m³

3. Point Density Thresholds:
   - Minimum points per bin
   - Ensures statistical validity
   - Typically 0.1% of total points

DATA PROCESSING CONCEPTS
----------------------
1. Raster Processing:
   - Spatial resolution: Typically 5m
   - Value type: Float32
   - NoData handling: 0 or null
   - Compression: DEFLATE

2. Height Normalization:
   - Reference: Ground level
   - Method: Nearest neighbor or TIN
   - Handles: Terrain variation

3. Vegetation Classification:
   - Classes 3-5: Vegetation
   - Class 3: Low vegetation
   - Class 4: Medium vegetation
   - Class 5: High vegetation

MATHEMATICAL TRANSFORMATIONS
--------------------------
1. NRD to PAD:
   PAD = -ln(1 - NRD)/(κ · Δz)
   - Based on Beer-Lambert law
   - Accounts for cumulative effects
   - Preserves physical meaning

2. Transmittance:
   T = 1 - NRD
   - Direct relationship
   - Used in validation
   - Physical interpretation

OUTPUT METRICS
------------
1. PAD Profiles:
   - Vertical distribution
   - Height-specific density
   - Ecosystem structure

2. Integrated Metrics:
   - Total plant area
   - Canopy height
   - Vertical complexity

REFERENCES
---------
1. Beer-Lambert Law: Fundamentals of Atmospheric Physics
2. LiDAR Processing: ASPRS Guidelines
3. Vegetation Structure: Forest Ecology Literature
4. PAD Calculation: Remote Sensing Applications
"""

# -------------------------------------------------------------------------
# IMPORTS AND DEPENDENCIES
# -------------------------------------------------------------------------

import os
import csv
import glob
import numpy as np
import pandas as pd
import argparse
import logging
import matplotlib.pyplot as plt
from typing import List, Dict, Union, Optional, Tuple
from pathlib import Path
from osgeo import gdal, osr
import multiprocessing
from concurrent.futures import ProcessPoolExecutor, as_completed
import time

# -------------------------------------------------------------------------
# USER-CONFIGURABLE PARAMETERS
# -------------------------------------------------------------------------

# Default input and output directories
# These should point to where your NRD files are located and where to save PAD results
DEFAULT_INPUT_DIR = r"C:\Users\user\Desktop\UvA\YEAR 2\Thesis\LiDAR\Analysis files\Processed\NRD Raster Layers"
DEFAULT_OUTPUT_DIR = r"C:\Users\user\Desktop\UvA\YEAR 2\Thesis\LiDAR\Analysis files\Processed\PAD Results"

# Default extinction coefficient (κ)
# This is a species-specific parameter that can vary between ecosystems:
# - Coniferous forests: typically 0.5-0.7
# - Deciduous forests: typically 0.4-0.6
# - Mixed forests: typically 0.5
# - Shrublands: typically 0.3-0.5
DEFAULT_EXTINCTION_COEFFICIENT = 0.6  # Using 0.6 as this is appropriate for mixed/deciduous forest

# Minimum allowed PAD value to avoid instability with very high NRD values
# that might lead to unrealistic PAD due to logarithm behavior near 1.0
MIN_PAD_VALUE = 0.1  # m²/m³

# Maximum allowed PAD value to filter out unrealistic high values
# that might occur from computation or data artifacts
MAX_PAD_VALUE = 10.0  # m²/m³ (adjust based on ecosystem)

# Default bin size in meters (if cannot be inferred from data)
DEFAULT_BIN_SIZE = 2.0  # m

# Whether to use parallel processing for multiple files
DEFAULT_PARALLEL_PROCESSING = True

# Maximum number of worker processes (None = use CPU count)
DEFAULT_MAX_WORKERS = 4

# -------------------------------------------------------------------------
# LOGGING CONFIGURATION
# -------------------------------------------------------------------------

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# -------------------------------------------------------------------------
# CORE FUNCTIONS
# -------------------------------------------------------------------------

def calculate_pad_from_nrd(nrd_value: float, 
                           extinction_coefficient: float = DEFAULT_EXTINCTION_COEFFICIENT, 
                           bin_size: float = 2.0) -> float:
    """
    Calculate Plant Area Density (PAD) from Normalized Return Density (NRD) using Beer-Lambert law.
    
    Args:
        nrd_value: Normalized Return Density value for a specific height bin
        extinction_coefficient: Light extinction coefficient (κ), depends on canopy structure
        bin_size: Height bin size in meters (Δz)
        
    Returns:
        float: PAD value in m²/m³
    """
    # Handle edge cases
    if nrd_value <= 0:
        return 0.0
    
    # Ensure NRD doesn't exceed 1.0 (which would cause issues with logarithm)
    nrd_value = min(nrd_value, 0.9999)
    
    # Calculate PAD using the Beer-Lambert law equation
    # PAD(z) = -ln(1 - NRD(z))/(κ · Δz)
    pad_value = -np.log(1 - nrd_value) / (extinction_coefficient * bin_size)
    
    # Bound PAD values to reasonable range
    pad_value = max(MIN_PAD_VALUE, min(pad_value, MAX_PAD_VALUE))
    
    return pad_value

def calculate_transmittance(nrd_value: float) -> float:
    """
    Calculate transmittance (gap fraction) from NRD.
    
    Transmittance is directly related to NRD as: Gf = 1 - NRD
    
    Args:
        nrd_value: Normalized Return Density value
        
    Returns:
        float: Transmittance (gap fraction) value (0-1)
    """
    # Ensure NRD doesn't exceed 1.0
    nrd_value = min(max(nrd_value, 0.0), 1.0)
    return 1.0 - nrd_value

def create_readme(output_dir: str, extinction_coefficient: float, bin_size: float) -> None:
    """
    Create a detailed README file in the output directory explaining the PAD calculation process,
    file formats, and visualization instructions.
    
    Args:
        output_dir: Directory where the README will be saved
        extinction_coefficient: The κ value used in calculations
        bin_size: Height bin size in meters
    """
    readme_path = os.path.join(output_dir, "README_PAD_CALCULATION.txt")
    
    # Use UTF-8 encoding for special characters
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write("""PLANT AREA DENSITY (PAD) CALCULATION
==============================

This directory contains Plant Area Density (PAD) calculations derived from LiDAR data
using the Beer-Lambert law approach. PAD represents the distribution of vegetation
material in three-dimensional space.

THEORETICAL BACKGROUND
--------------------
The Beer-Lambert law describes light attenuation through a medium:
I = I₀ e^(-κL)

Where:
- I = Transmitted light intensity
- I₀ = Initial light intensity
- κ = Extinction coefficient
- L = Path length

For vegetation structure analysis, this is transformed to calculate PAD:
PAD(z) = -ln(1 - NRD(z))/(κ · Δz)

Where:
- PAD(z) = Plant Area Density at height z (m²/m³)
- NRD(z) = Normalized Return Density at height z
- κ = Extinction coefficient (species-specific)
- Δz = Height bin size (m)

USER-CONFIGURABLE PARAMETERS
-------------------------
1. Extinction Coefficient (κ):
   Current value: {0:.2f}
   - Species-specific parameter affecting PAD magnitude
   - Typical ranges by vegetation type:
     * Coniferous forests: 0.5-0.7
     * Deciduous forests: 0.4-0.6
     * Mixed forests: ~0.5
     * Shrublands: 0.3-0.5
   - Higher values = Lower PAD estimates
   - Lower values = Higher PAD estimates

2. Height Bin Size:
   Current value: {1:.1f}m
   - Vertical resolution of analysis
   - Affects PAD magnitude inversely
   - Trade-off: Resolution vs. point density
   - Recommended: 1-2m for dense data, 2-5m for sparse

3. PAD Value Bounds:
   - Minimum: {2:.1f} m²/m³
     * Prevents negative values
     * Physical constraint (no negative density)
   - Maximum: {3:.1f} m²/m³
     * Prevents unrealistic high values
     * Adjustable based on ecosystem

4. Input/Output Directories:
   Default input: {4}
   Default output: {5}
   - Can be overridden via command line
   - Maintains relative paths in subdirectories

5. Visualization Options:
   - Multi-panel plots enabled by default
   - Can be disabled with --no_viz flag
   - DPI: 300 for high-quality output
   - Standard figure size: 12x8 inches

6. Raster Processing:
   - Format: 32-bit float GeoTIFF
   - Compression: DEFLATE
   - Tiling: Enabled for performance
   - NoData value: 0

PROCESSING PARAMETERS
-------------------
Current processing used:
- Extinction coefficient (κ) = {0:.2f}
- Height bin size = {1:.1f}m
- PAD value range: {2:.1f}-{3:.1f} m²/m³

FILE DESCRIPTIONS
---------------
1. CSV Files:
   - *_pad_values.csv: Contains height-specific PAD values
     Columns: Height (m), NRD Value, Transmittance, PAD (m²/m³)

2. Raster Files (in pad_rasters/):
   - *_pad_[height].tif: PAD values for each height bin
   - Values represent PAD in m²/m³
   - NoData value = 0

3. Visualization Files:
   - *_pad_visualization.png: Multi-panel plot showing:
     * NRD values vs height
     * Transmittance vs height
     * PAD values vs height
   - *_all_pad_layers.vrt: Combined view of all PAD layers

QGIS VISUALIZATION INSTRUCTIONS
----------------------------
To visualize PAD rasters in QGIS:

1. Individual height layers:
   - Open .tif files from pad_rasters/ folder
   - Set symbology to "Singleband pseudocolor"
   - Set min/max values to {2:.1f}-{3:.1f} for consistent scale
   - Suggested color ramp: Viridis or Spectral

2. Combined visualization:
   - Open the .vrt file
   - Use "Multiband color" to create RGB composites
   - Try different band combinations to highlight structure

UNDERSTANDING THE VALUES
----------------------
- PAD values are in m²/m³ (plant material per unit volume)
- Higher values indicate denser vegetation
- Typical ranges:
  * Dense forest: 0.5-2.0 m²/m³
  * Open woodland: 0.1-0.5 m²/m³
  * Shrubland: 0.05-0.3 m²/m³

QUALITY CONTROL
-------------
- Values are bounded between {2:.1f}-{3:.1f} m²/m³
- Areas with no vegetation return PAD = 0
- Statistical filtering removes outliers
- Minimum point density thresholds applied

COMMAND LINE USAGE
----------------
Basic usage:
python PAD_calculation.py [options]

Options:
--nrd_file PATH      Process single NRD file
--input_dir PATH     Process directory of NRD files
--output_dir PATH    Custom output location
--extinction VALUE   Set extinction coefficient
--no_viz            Skip visualization plots

Example:
python PAD_calculation.py --input_dir /path/to/nrd/files --extinction 0.6

For more information about the methodology, refer to:
1. Beer-Lambert Law: Fundamentals of Atmospheric Physics
2. LiDAR Processing: ASPRS LiDAR Guidelines
3. Vegetation Structure: Forest Ecology Literature
""".format(extinction_coefficient, bin_size, 
           MIN_PAD_VALUE, MAX_PAD_VALUE,
           DEFAULT_INPUT_DIR, DEFAULT_OUTPUT_DIR))
        
        logger.info(f"Created README file: {readme_path}")

def process_nrd_file(nrd_file_path: str, 
                     output_dir: str = None,
                     extinction_coefficient: float = DEFAULT_EXTINCTION_COEFFICIENT,
                     create_visualizations: bool = True) -> pd.DataFrame:
    """
    Process an NRD CSV file to calculate PAD values.
    
    Args:
        nrd_file_path: Path to the NRD CSV file (*_nrd_values.csv)
        output_dir: Directory to save output files (defaults to same as input)
        extinction_coefficient: Light extinction coefficient (κ)
        create_visualizations: Whether to create visualization plots
        
    Returns:
        pd.DataFrame: DataFrame with height, NRD, and PAD values
    """
    logger.info(f"\n{'='*80}")
    logger.info(f"Starting to process NRD file: {nrd_file_path}")
    logger.info(f"{'='*80}")

    # Setup output directory
    if output_dir is None:
        # Get the parent directory of the NRD file's directory
        parent_dir = os.path.dirname(os.path.dirname(nrd_file_path))
        # Get the dataset name (directory name containing the NRD file)
        dataset_name = os.path.basename(os.path.dirname(nrd_file_path))
        # Create corresponding output directory
        output_dir = os.path.join(DEFAULT_OUTPUT_DIR, dataset_name)
    
    logger.info(f"Using output directory: {output_dir}")
    os.makedirs(output_dir, exist_ok=True)
    
    # Extract file name for output naming
    file_name = os.path.splitext(os.path.basename(nrd_file_path))[0]
    dataset_base = file_name.replace('_nrd_values', '')
    logger.info(f"Dataset base name: {dataset_base}")
    
    # Check for corresponding NRD rasters directory
    nrd_dir = os.path.dirname(nrd_file_path)
    nrd_raster_dir = os.path.join(nrd_dir, "nrd_rasters")
    logger.info(f"Looking for NRD rasters in: {nrd_raster_dir}")
    
    if not os.path.exists(nrd_raster_dir):
        logger.error(f"NRD raster directory not found: {nrd_raster_dir}")
        logger.error("Cannot calculate PAD values without true NRD rasters")
        return None
    
    # Count NRD raster files
    nrd_raster_files = glob.glob(os.path.join(nrd_raster_dir, f"{dataset_base}_nrd_*.tif"))
    logger.info(f"Found {len(nrd_raster_files)} NRD raster files")
    if len(nrd_raster_files) == 0:
        logger.error(f"No NRD raster files found matching pattern: {dataset_base}_nrd_*.tif")
        return None
    
    # Create PAD output directories
    pad_raster_dir = os.path.join(output_dir, "pad_rasters")
    logger.info(f"Creating PAD raster directory: {pad_raster_dir}")
    os.makedirs(pad_raster_dir, exist_ok=True)
    
    # Read the NRD CSV file
    logger.info(f"Reading NRD values from CSV file: {nrd_file_path}")
    try:
        # Skip any notes (metadata) in the CSV file
        with open(nrd_file_path, 'r') as f:
            first_line = f.readline().strip()
            has_header = first_line.startswith('Height')
            logger.info(f"CSV has header: {has_header}")
        
        if has_header:
            # Read with pandas if it has a proper header
            df = pd.read_csv(nrd_file_path)
            # Filter out any non-data rows (notes, etc.)
            df = df[pd.to_numeric(df['Height (m)'], errors='coerce').notna()]
            # Convert height and NRD values to float
            df['Height (m)'] = pd.to_numeric(df['Height (m)'], errors='coerce')
            df['NRD Value'] = pd.to_numeric(df['NRD Value'], errors='coerce')
            logger.info(f"Successfully read {len(df)} height bins from CSV")
        else:
            # Fall back to manual parsing
            heights = []
            nrd_values = []
            with open(nrd_file_path, 'r') as f:
                csv_reader = csv.reader(f)
                header_found = False
                for row in csv_reader:
                    if len(row) >= 2 and row[0] == 'Height (m)':
                        header_found = True
                        continue
                    if header_found and len(row) >= 2:
                        try:
                            height = float(row[0])
                            nrd = float(row[1])
                            heights.append(height)
                            nrd_values.append(nrd)
                        except ValueError:
                            continue
            df = pd.DataFrame({'Height (m)': heights, 'NRD Value': nrd_values})
            logger.info(f"Successfully read {len(df)} height bins from CSV using manual parsing")
        
        # Check if we have data
        if len(df) == 0:
            logger.error(f"No valid data found in {nrd_file_path}")
            return None
        
        # Calculate PAD for each height
        logger.info(f"Calculating PAD values with extinction coefficient κ={extinction_coefficient}")
        
        # Add columns for transmittance and PAD
        df['Transmittance'] = df['NRD Value'].apply(calculate_transmittance)
        df['PAD (m²/m³)'] = df.apply(lambda row: calculate_pad_from_nrd(
            row['NRD Value'], extinction_coefficient, DEFAULT_BIN_SIZE), axis=1)
        
        logger.info(f"Height range: {df['Height (m)'].min():.1f}m - {df['Height (m)'].max():.1f}m")
        logger.info(f"PAD value range: {df['PAD (m²/m³)'].min():.3f} - {df['PAD (m²/m³)'].max():.3f} m²/m³")
        
        # Save the results to a new CSV file
        output_file = os.path.join(output_dir, f"{dataset_base}_pad_values.csv")
        logger.info(f"Saving PAD values to CSV: {output_file}")
        
        with open(output_file, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(['Height (m)', 'NRD Value', 'Transmittance', 'PAD (m²/m³)'])
            writer.writerow(['Parameters', f'Extinction coefficient (κ)={extinction_coefficient}', 
                            f'Bin size={DEFAULT_BIN_SIZE}m', f'Formula: PAD=-ln(1-NRD)/(κ·Δz)'])
            for _, row in df.iterrows():
                writer.writerow([row['Height (m)'], row['NRD Value'], 
                                row['Transmittance'], row['PAD (m²/m³)']])
        
        logger.info(f"Successfully saved PAD values to {output_file}")
        
        # Create visualization if requested
        if create_visualizations:
            logger.info("Creating PAD visualization plots...")
            create_pad_visualization(df, dataset_base, output_dir, extinction_coefficient, DEFAULT_BIN_SIZE)
        
        # Create rasters with PAD values
        logger.info("Creating PAD raster files...")
        create_pad_rasters(dataset_base, output_dir, df, extinction_coefficient)
        
        logger.info(f"\n{'='*80}")
        logger.info("Processing completed successfully!")
        logger.info(f"Output directory: {output_dir}")
        logger.info(f"{'='*80}")
        
        return df
    
    except Exception as e:
        logger.error(f"Error processing {nrd_file_path}: {str(e)}")
        import traceback
        logger.error(f"Full traceback:\n{traceback.format_exc()}")
        return None

def create_pad_visualization(df: pd.DataFrame, 
                            dataset_name: str, 
                            output_dir: str,
                            extinction_coefficient: float,
                            bin_size: float) -> None:
    """
    Create visualization of PAD values versus height.
    
    Args:
        df: DataFrame with height, NRD, and PAD values
        dataset_name: Base name for output files
        output_dir: Directory to save output
        extinction_coefficient: Light extinction coefficient (κ)
        bin_size: Height bin size in meters
    """
    try:
        plt.figure(figsize=(12, 8))
        
        # Plot 1: NRD values
        plt.subplot(1, 3, 1)
        plt.plot(df['NRD Value'], df['Height (m)'], 'o-', color='blue', linewidth=2)
        plt.title('Normalized Return Density (NRD)')
        plt.xlabel('NRD Value')
        plt.ylabel('Height (m)')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, 1)
        
        # Plot 2: Transmittance (Gap Fraction)
        plt.subplot(1, 3, 2)
        plt.plot(df['Transmittance'], df['Height (m)'], 'o-', color='green', linewidth=2)
        plt.title('Transmittance (Gap Fraction)')
        plt.xlabel('Transmittance (1 - NRD)')
        plt.ylabel('Height (m)')
        plt.grid(True, alpha=0.3)
        plt.xlim(0, 1)
        
        # Plot 3: PAD values
        plt.subplot(1, 3, 3)
        plt.plot(df['PAD (m²/m³)'], df['Height (m)'], 'o-', color='red', linewidth=2)
        plt.title('Plant Area Density (PAD)')
        plt.xlabel('PAD (m²/m³)')
        plt.ylabel('Height (m)')
        plt.grid(True, alpha=0.3)
        max_pad = df['PAD (m²/m³)'].max() * 1.1
        plt.xlim(0, max(max_pad, 1.0))
        
        # Add parameters in a text box
        plt.figtext(0.5, 0.01, 
                   f"Parameters: Extinction coefficient (κ)={extinction_coefficient}, "
                   f"Bin size={bin_size}m, Formula: PAD=-ln(1-NRD)/(κ·Δz)",
                   ha='center', fontsize=10, bbox=dict(facecolor='lightgray', alpha=0.5))
        
        # Adjust layout and save the plot
        plt.tight_layout(rect=[0, 0.03, 1, 0.97])
        plot_path = os.path.join(output_dir, f"{dataset_name}_pad_visualization.png")
        plt.savefig(plot_path, dpi=300)
        plt.close()
        
        logger.info(f"Created PAD visualization: {plot_path}")
    
    except Exception as e:
        logger.error(f"Error creating visualization: {str(e)}")

def create_pad_rasters(dataset_name: str, output_dir: str, pad_data: pd.DataFrame, 
                      extinction_coefficient: float) -> None:
    """
    Create raster files with PAD values for each height bin by directly applying
    the Beer-Lambert law to true NRD raster values.
    
    This function uses the true NRD rasters created by NRD_calculation.py, which 
    contain actual NRD values calculated as:
    NRD = points in bin / (points in bin and all bins below).
    
    Args:
        dataset_name: Base name of the dataset
        output_dir: Directory to save output
        pad_data: DataFrame with height and PAD values
        extinction_coefficient: Light extinction coefficient (κ) used in PAD calculation
    """
    # Get the parent directory of the output directory to find the NRD directory
    nrd_base_dir = os.path.dirname(os.path.dirname(output_dir))
    nrd_dir = os.path.join(nrd_base_dir, "NRD Raster Layers", os.path.basename(output_dir))
    nrd_raster_dir = os.path.join(nrd_dir, "nrd_rasters")
    
    if not os.path.exists(nrd_raster_dir):
        logger.error(f"NRD raster directory not found: {nrd_raster_dir}")
        logger.error("Cannot calculate PAD values without true NRD rasters")
        return
    
    # Create PAD raster directory
    pad_raster_dir = os.path.join(output_dir, "pad_rasters")
    os.makedirs(pad_raster_dir, exist_ok=True)
    
    # Find all NRD raster files
    raster_files = glob.glob(os.path.join(nrd_raster_dir, f"{dataset_name}_nrd_*.tif"))
    if not raster_files:
        logger.warning(f"No true NRD raster files found for {dataset_name}")
        logger.info(f"Searched in: {nrd_raster_dir}")
        logger.info(f"Looking for pattern: {dataset_name}_nrd_*.tif")
        return
    
    logger.info(f"Found {len(raster_files)} NRD raster files to process")
    
    # Process each raster file
    vrt_sources = []
    for i, raster_file in enumerate(raster_files, 1):
        try:
            logger.info(f"\nProcessing raster {i}/{len(raster_files)}: {os.path.basename(raster_file)}")
            
            # Extract height from filename
            height_info = os.path.basename(raster_file).split('_nrd_')[1].split('.tif')[0]
            if 'to' in height_info:
                min_height = float(height_info.split('m_to_')[0])
            else:
                # Alternative format: nrd_0.0-2.0m.tif
                min_height = float(height_info.split('-')[0])
            
            logger.info(f"Height bin starting at {min_height:.1f}m")
            
            # Open the NRD raster file
            src_ds = gdal.Open(raster_file)
            if src_ds is None:
                logger.error(f"Could not open raster file: {raster_file}")
                continue
            
            # Get raster properties
            width = src_ds.RasterXSize
            height = src_ds.RasterYSize
            logger.info(f"Raster dimensions: {width}x{height} pixels")
            
            # Read the NRD raster data
            band = src_ds.GetRasterBand(1)
            nrd_data = band.ReadAsArray()
            
            # Create PAD raster file path
            pad_raster_file = os.path.join(pad_raster_dir, f"{dataset_name}_pad_{min_height:.1f}m.tif")
            vrt_sources.append(pad_raster_file)
            
            # Calculate PAD values
            logger.info("Calculating PAD values from NRD data...")
            pad_raster = np.zeros_like(nrd_data, dtype=np.float32)
            
            # Create mask for non-zero values
            mask = nrd_data > 0
            
            # For true NRD rasters: directly apply Beer-Lambert law
            nrd_values = nrd_data[mask]
            
            # Clip NRD values to avoid numerical instability
            nrd_values = np.clip(nrd_values, 0, 0.9999)
            
            # Apply Beer-Lambert directly: PAD = -ln(1-NRD)/(κ·Δz)
            pad_raster[mask] = -np.log(1 - nrd_values) / (extinction_coefficient * DEFAULT_BIN_SIZE)
            
            # Bound PAD values to reasonable range
            pad_raster[mask] = np.clip(pad_raster[mask], MIN_PAD_VALUE, MAX_PAD_VALUE)
            
            # Set no data value
            pad_raster[~mask] = 0  # Set areas with no vegetation to 0 PAD
            
            logger.info(f"PAD value range: {np.min(pad_raster[mask]):.3f} - {np.max(pad_raster[mask]):.3f} m²/m³")
            
            # Create the output raster file
            logger.info("Creating output raster file...")
            driver = gdal.GetDriverByName('GTiff')
            dst_ds = driver.Create(
                pad_raster_file,
                width,
                height,
                1,  # Number of bands
                gdal.GDT_Float32,
                options=['COMPRESS=DEFLATE', 'TILED=YES']
            )
            
            # Copy georeference information
            dst_ds.SetGeoTransform(src_ds.GetGeoTransform())
            dst_ds.SetProjection(src_ds.GetProjection())
            
            # Write the PAD data
            dst_band = dst_ds.GetRasterBand(1)
            dst_band.WriteArray(pad_raster)
            dst_band.SetNoDataValue(0)
            dst_band.SetDescription(f"Plant Area Density at height {min_height:.1f}m")
            
            # Compute statistics
            dst_band.ComputeStatistics(False)
            
            # Cleanup
            dst_band = None
            dst_ds = None
            src_ds = None
            
            logger.info(f"Created PAD raster: {pad_raster_file}")
            
        except Exception as e:
            logger.error(f"Error creating PAD raster for {os.path.basename(raster_file)}: {str(e)}")
            import traceback
            logger.error(traceback.format_exc())
            continue
    
    # Create a VRT file for all PAD layers
    if vrt_sources:
        logger.info("\nCreating combined VRT file for all PAD layers...")
        vrt_path = os.path.join(output_dir, f"{dataset_name}_all_pad_layers.vrt")
        vrt_options = gdal.BuildVRTOptions(separate=True)
        gdal.BuildVRT(vrt_path, vrt_sources, options=vrt_options)
        logger.info(f"Created VRT file: {vrt_path}")
    else:
        logger.warning("No PAD rasters were created successfully")

def process_directory(input_dir: str, 
                     output_base_dir: str = None,
                     extinction_coefficient: float = DEFAULT_EXTINCTION_COEFFICIENT,
                     create_visualizations: bool = True,
                     parallel_processing: bool = DEFAULT_PARALLEL_PROCESSING,
                     num_workers: int = DEFAULT_MAX_WORKERS) -> None:
    """
    Process all NRD files in a directory to calculate PAD values.
    
    Args:
        input_dir: Directory containing NRD CSV files
        output_base_dir: Base directory to save output (default: input_dir)
        extinction_coefficient: Light extinction coefficient (κ)
        create_visualizations: Whether to create visualization plots
        parallel_processing: Whether to use parallel processing
        num_workers: Number of worker processes to use
    """
    if output_base_dir is None:
        output_base_dir = DEFAULT_OUTPUT_DIR
    
    # Create output base directory if it doesn't exist
    os.makedirs(output_base_dir, exist_ok=True)
    
    # Create README in the base output directory
    create_readme(output_base_dir, extinction_coefficient, DEFAULT_BIN_SIZE)
    
    # Find all dataset directories in the input directory
    dataset_dirs = [d for d in glob.glob(os.path.join(input_dir, "*")) if os.path.isdir(d)]
    
    if not dataset_dirs:
        logger.error(f"No dataset directories found in {input_dir}")
        return
    
    logger.info(f"Found {len(dataset_dirs)} dataset directories to process")
    
    # Process each dataset directory
    for dataset_dir in dataset_dirs:
        dataset_name = os.path.basename(dataset_dir)
        logger.info(f"\nProcessing dataset: {dataset_name}")
        
        # Find NRD CSV files in this dataset directory
        nrd_files = glob.glob(os.path.join(dataset_dir, "*_nrd_values.csv"))
        
        if not nrd_files:
            logger.warning(f"No NRD CSV files found in {dataset_dir}")
            continue
        
        # Create output directory for this dataset
        dataset_output_dir = os.path.join(output_base_dir, dataset_name)
        os.makedirs(dataset_output_dir, exist_ok=True)
        
        # Check for NRD raster directory
        nrd_raster_dir = os.path.join(dataset_dir, "nrd_rasters")
        if not os.path.exists(nrd_raster_dir):
            logger.error(f"NRD raster directory not found: {nrd_raster_dir}")
            logger.info("Expected directory structure:")
            logger.info(f"{dataset_dir}/")
            logger.info("  ├── *_nrd_values.csv")
            logger.info("  └── nrd_rasters/")
            logger.info("      └── *_nrd_*.tif")
            continue
        
        # Count NRD raster files
        nrd_raster_files = glob.glob(os.path.join(nrd_raster_dir, "*_nrd_*.tif"))
        logger.info(f"Found {len(nrd_files)} NRD CSV files and {len(nrd_raster_files)} NRD raster files")
        
        # Process files for this dataset
        start_time = time.time()
        results = []
        
        if parallel_processing and len(nrd_files) > 1:
            with ProcessPoolExecutor(max_workers=num_workers) as executor:
                # Submit all tasks
                future_to_file = {}
                for nrd_file in nrd_files:
                    # Submit task
                    future = executor.submit(
                        process_nrd_file,
                        nrd_file,
                        dataset_output_dir,
                        extinction_coefficient,
                        create_visualizations
                    )
                    future_to_file[future] = nrd_file
                
                # Process results as they complete
                completed = 0
                for future in as_completed(future_to_file):
                    completed += 1
                    file = future_to_file[future]
                    try:
                        result = future.result()
                        if result is not None:
                            logger.info(f"[{completed}/{len(nrd_files)}] Successfully processed {os.path.basename(file)}")
                            results.append((file, True))
                        else:
                            logger.error(f"[{completed}/{len(nrd_files)}] Failed to process {os.path.basename(file)}")
                            results.append((file, False))
                    except Exception as e:
                        logger.error(f"[{completed}/{len(nrd_files)}] Error processing {os.path.basename(file)}: {str(e)}")
                        results.append((file, False))
                    
                    # Calculate and display progress
                    elapsed_time = time.time() - start_time
                    avg_time_per_file = elapsed_time / completed
                    remaining_files = len(nrd_files) - completed
                    estimated_remaining_time = avg_time_per_file * remaining_files
                    
                    logger.info(f"Progress: {completed}/{len(nrd_files)} files ({(completed/len(nrd_files))*100:.1f}%)")
                    logger.info(f"Average time per file: {avg_time_per_file:.1f} seconds")
                    logger.info(f"Estimated time remaining: {estimated_remaining_time/60:.1f} minutes")
        else:
            # Process sequentially
            for i, nrd_file in enumerate(nrd_files, 1):
                try:
                    logger.info(f"\nProcessing file {i}/{len(nrd_files)}: {os.path.basename(nrd_file)}")
                    
                    # Process file
                    result = process_nrd_file(nrd_file, dataset_output_dir, extinction_coefficient, create_visualizations)
                    if result is not None:
                        logger.info(f"[{i}/{len(nrd_files)}] Successfully processed {os.path.basename(nrd_file)}")
                        results.append((nrd_file, True))
                    else:
                        logger.error(f"[{i}/{len(nrd_files)}] Failed to process {os.path.basename(nrd_file)}")
                        results.append((nrd_file, False))
                    
                    # Calculate and display progress
                    elapsed_time = time.time() - start_time
                    avg_time_per_file = elapsed_time / i
                    remaining_files = len(nrd_files) - i
                    estimated_remaining_time = avg_time_per_file * remaining_files
                    
                    logger.info(f"Progress: {i}/{len(nrd_files)} files ({(i/len(nrd_files))*100:.1f}%)")
                    logger.info(f"Average time per file: {avg_time_per_file:.1f} seconds")
                    logger.info(f"Estimated time remaining: {estimated_remaining_time/60:.1f} minutes")
                    
                except Exception as e:
                    logger.error(f"[{i}/{len(nrd_files)}] Error processing {os.path.basename(nrd_file)}: {str(e)}")
                    results.append((nrd_file, False))
        
        # Summarize results for this dataset
        end_time = time.time()
        elapsed_time = end_time - start_time
        
        successful = [r for r in results if r[1]]
        failed = [r for r in results if not r[1]]
        
        logger.info(f"\nDataset {dataset_name} processing complete!")
        logger.info(f"Total time: {elapsed_time:.2f} seconds ({elapsed_time/60:.1f} minutes)")
        logger.info(f"Files processed: {len(results)}")
        logger.info(f"Successfully processed: {len(successful)}")
        logger.info(f"Failed: {len(failed)}")
        
        if failed:
            logger.info("\nFailed files:")
            for filename, _ in failed:
                logger.info(f"- {os.path.basename(filename)}")
                
        # Check output
        if len(successful) > 0:
            logger.info("\nChecking output files...")
            pad_raster_dir = os.path.join(dataset_output_dir, "pad_rasters")
            if os.path.exists(pad_raster_dir):
                pad_rasters = glob.glob(os.path.join(pad_raster_dir, "*_pad_*.tif"))
                logger.info(f"Found {len(pad_rasters)} PAD raster files in output directory")
            else:
                logger.warning("No PAD raster directory found in output")
                
            pad_csv_files = glob.glob(os.path.join(dataset_output_dir, "*_pad_values.csv"))
            logger.info(f"Found {len(pad_csv_files)} PAD CSV files in output directory")

def main():
    """Main function for command-line execution."""
    parser = argparse.ArgumentParser(description='Calculate Plant Area Density (PAD) from Normalized Return Density (NRD) values')
    
    # Input/output arguments
    input_group = parser.add_mutually_exclusive_group(required=False)  # Changed to not required so defaults can be used
    input_group.add_argument('--nrd_file', type=str, help='Path to an NRD CSV file')
    input_group.add_argument('--input_dir', type=str, help=f'Directory containing NRD CSV files (default: {DEFAULT_INPUT_DIR})')
    
    parser.add_argument('--output_dir', type=str, help=f'Directory to save output (default: {DEFAULT_OUTPUT_DIR} or same as input)')
    parser.add_argument('--extinction', type=float, default=DEFAULT_EXTINCTION_COEFFICIENT, 
                       help=f'Extinction coefficient (κ) (default: {DEFAULT_EXTINCTION_COEFFICIENT})')
    parser.add_argument('--no_viz', action='store_true', help='Skip creating visualization plots')
    
    # Add parallel processing arguments
    parser.add_argument('--no_parallel', action='store_true', 
                       help='Disable parallel processing')
    parser.add_argument('--workers', type=int, default=DEFAULT_MAX_WORKERS,
                       help=f'Number of parallel workers (default: {DEFAULT_MAX_WORKERS})')
    
    args = parser.parse_args()
    
    # Use default directories if not specified
    input_dir = args.input_dir if args.input_dir else DEFAULT_INPUT_DIR
    output_dir = args.output_dir if args.output_dir else DEFAULT_OUTPUT_DIR
    
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Process the input
    if args.nrd_file:
        # Process a single NRD file
        process_nrd_file(args.nrd_file, output_dir, args.extinction, not args.no_viz)
    else:
        # Process a directory of NRD files
        process_directory(
            input_dir, 
            output_dir, 
            args.extinction, 
            not args.no_viz,
            not args.no_parallel,
            args.workers
        )
        
    logger.info("PAD calculation completed successfully.")
    logger.info(f"Output saved to: {output_dir}")

if __name__ == "__main__":
    main() 