#!/usr/bin/env python3

print('🔍 ANALYZING CALIBRATION FAILURE PATTERN')
print('=' * 50)

print('📊 CALIBRATION RESULTS ANALYSIS:')
print('Best objective: 0.98567660 (98.6% error)')
print('Parameters found:')
print('  - min_fuel_value: 0.10 (MEDIUM)')
print('  - spread_probability: 0.95 (MAXIMUM)')
print('  - fuel_consumption_rate: 0.30 (LOW)')
print('  - ember_probability: 0.60 (HIGH)')
print()

print('🚨 CRITICAL OBSERVATION:')
print('1. Some simulations: "No active cells at start" → 1 cell burned')
print('2. Other simulations: 2,000-11,000 cells burned')
print('3. Still hitting spread_probability = 0.95 (maximum)')
print('4. Error barely improved: 0.984 → 0.986')
print()

print('💡 POSSIBLE REMAINING ISSUES:')
print('A) TARGET DATA SIZE MISMATCH:')
print('   - 20-step simulation: 2k-11k cells')
print('   - EMSR Days 1-2: How many cells?')
print('   - Size ratio could still be completely wrong')
print()
print('B) COORDINATE SYSTEM STILL WRONG:')
print('   - Simulation may not be using LiDAR coordinate system')
print('   - Target rasterization may be using different coordinates')
print('   - Need to verify actual grid alignment')
print()
print('C) TARGET DATA PROCESSING ISSUE:')
print('   - Target may be empty/corrupted')
print('   - Target may be in wrong format')
print('   - Need to check target data size and content')
print()

print('🔍 IMMEDIATE DIAGNOSTICS NEEDED:')
print('1. What is the size of the target data? (how many cells)')
print('2. What is the size of simulation results? (we see 2k-11k)')
print('3. Are they using the same coordinate system?')
print('4. Is there ANY spatial overlap at all?')

print()
print('🎯 NEXT INVESTIGATION:')
print('Check the most recent calibration results to see:')
print('- Target data size and content')
print('- Actual spatial overlap numbers')
print('- Whether Dice calculation is working correctly')
print('- Whether target data is being loaded properly')
