#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Preprocessed Terrain Validation Script

This script validates the correctness and quality of preprocessed terrain outputs
generated by the terrain preprocessor. It performs comprehensive checks on file
integrity, data quality, spatial consistency, and statistical analysis.

Author: Forest Fire Simulation Team
Date: 2025
Version: 1.0
"""

import os
import sys
import json
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Dict, List, Tuple, Any, Optional
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

class TerrainValidationError(Exception):
    """Custom exception for terrain validation errors."""
    pass

class PreprocessedTerrainValidator:
    """Comprehensive validator for preprocessed terrain outputs."""
    
    def __init__(self, preprocessed_dir: str):
        """
        Initialize the validator.
        
        Args:
            preprocessed_dir: Path to the preprocessed terrain directory
        """
        self.preprocessed_dir = Path(preprocessed_dir)
        self.validation_results = {
            'overall_status': 'UNKNOWN',
            'file_integrity': {},
            'data_quality': {},
            'spatial_consistency': {},
            'statistical_analysis': {},
            'issues': [],
            'warnings': []
        }
        
        # Expected files and their properties
        self.expected_files = {
            'elevation.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'slope.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'aspect.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'barranco_mask.npy': {'dtype': np.bool_, 'min_size_mb': 50},
            'barranco_directions.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'depression_mask.npy': {'dtype': np.bool_, 'min_size_mb': 50},
            'wind_channeling_mask.npy': {'dtype': np.bool_, 'min_size_mb': 50},
            'wind_amplification.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'wind_direction_modification.npy': {'dtype': np.float32, 'min_size_mb': 100},
            'metadata.json': {'dtype': 'json', 'min_size_mb': 0.001},
            'processing_log.txt': {'dtype': 'text', 'min_size_mb': 0.001}
        }
        
        # Validation parameters for DTM that includes both sea and land areas
        VALIDATION_PARAMS = {
            # Elevation validation (includes sea level)
            'elevation': {
                'min_m': -1.0,  # Allow slightly below sea level
                'max_m': 3715.0,  # Allow slightly above Teide peak
                'min_file_size_mb': 0.001
            },
            
            # Slope validation (sea areas will have 0 slope)
            'slope': {
                'min_degrees': 0.0,
                'max_degrees': 90.0,
                'min_file_size_mb': 0.001
            },
            
            # Aspect validation (sea areas will have undefined aspect)
            'aspect': {
                'min_degrees': 0.0,
                'max_degrees': 360.0,
                'min_file_size_mb': 0.001
            },
            
            # Barranco detection validation (only on land)
            'barranco_detection': {
                'min_density': 1e-6,  # Very low - barrancos only on volcanic land
                'max_density': 0.01,  # Maximum 1% of cells can be barrancos
                'min_file_size_mb': 0.001
            },
            
            # Depression detection validation (includes sea areas)
            'depression_detection': {
                'min_density': 0.5,  # High - most cells are sea/ocean depressions
                'max_density': 0.9,  # Maximum 90% can be depressions
                'min_file_size_mb': 0.001
            },
            
            # Wind channeling validation (only on land features)
            'wind_channeling': {
                'min_density': 1e-6,  # Very low - only on land features
                'max_density': 0.01,  # Maximum 1% of cells
                'min_file_size_mb': 0.001
            },
            
            # Statistical validation for mixed sea/land DTM
            'statistical': {
                'elevation': {
                    'expected_median_range': (0.0, 50.0),  # Median should be near sea level
                    'expected_mean_range': (50.0, 500.0),  # Mean should be positive but not too high
                    'expected_std_range': (100.0, 1000.0)  # High std due to sea vs land contrast
                },
                'slope': {
                    'expected_median_range': (0.0, 5.0),  # Most cells are flat (sea)
                    'expected_mean_range': (5.0, 25.0),   # Mean pulled up by land slopes
                    'expected_steep_slopes_pct': (5.0, 30.0)  # 5-30% steep slopes on land
                }
            }
        }
    
    def validate_file_integrity(self) -> Dict[str, Any]:
        """Validate file existence, readability, and basic properties."""
        logger.info("🔍 Validating file integrity...")
        
        results = {}
        all_files_exist = True
        
        for filename, properties in self.expected_files.items():
            file_path = self.preprocessed_dir / filename
            file_result = {
                'exists': False,
                'readable': False,
                'size_mb': 0,
                'dtype_match': False,
                'issues': []
            }
            
            # Check file existence
            if file_path.exists():
                file_result['exists'] = True
                file_result['size_mb'] = file_path.stat().st_size / (1024 * 1024)
                
                # Check file size
                if file_result['size_mb'] < properties['min_size_mb']:
                    file_result['issues'].append(f"File too small: {file_result['size_mb']:.2f} MB < {properties['min_size_mb']} MB")
                
                # Try to read the file
                try:
                    if properties['dtype'] in [np.float32, np.bool_]:
                        data = np.load(file_path)
                        file_result['readable'] = True
                        
                        # Check data type
                        if data.dtype == properties['dtype']:
                            file_result['dtype_match'] = True
                        else:
                            file_result['issues'].append(f"Wrong dtype: expected {properties['dtype']}, got {data.dtype}")
                        
                        # Store data for later analysis
                        setattr(self, f'{filename.replace(".npy", "")}_data', data)
                        
                    elif properties['dtype'] == 'json':
                        with open(file_path, 'r') as f:
                            json.load(f)
                        file_result['readable'] = True
                        file_result['dtype_match'] = True
                        
                    elif properties['dtype'] == 'text':
                        with open(file_path, 'r') as f:
                            f.read()
                        file_result['readable'] = True
                        file_result['dtype_match'] = True
                        
                except Exception as e:
                    file_result['issues'].append(f"Error reading file: {e}")
            else:
                file_result['issues'].append("File does not exist")
                all_files_exist = False
            
            results[filename] = file_result
        
        self.validation_results['file_integrity'] = results
        
        if not all_files_exist:
            self.validation_results['issues'].append("Some expected files are missing")
        
        return results
    
    def validate_data_quality(self) -> Dict[str, Any]:
        """Validate data quality and ranges."""
        logger.info("📊 Validating data quality...")
        
        results = {}
        
        # Validate elevation data
        if hasattr(self, 'elevation_data'):
            elev_data = self.elevation_data
            elev_result = {
                'min': float(elev_data.min()),
                'max': float(elev_data.max()),
                'mean': float(elev_data.mean()),
                'std': float(elev_data.std()),
                'valid_range': True,
                'no_constant': True,
                'no_nan': True,
                'issues': []
            }
            
            # Check range
            if not (VALIDATION_PARAMS['elevation']['min_m'] <= elev_result['min'] <= elev_result['max'] <= VALIDATION_PARAMS['elevation']['max_m']):
                elev_result['valid_range'] = False
                elev_result['issues'].append(f"Elevation range {elev_result['min']:.1f}-{elev_result['max']:.1f}m outside expected range (-1.0 to 3715.0m)")
            
            # Check if maximum elevation is close to Mount Teide (3703m)
            if elev_result['max'] < 3600:
                elev_result['warnings'] = elev_result.get('warnings', [])
                elev_result['warnings'].append(f"Maximum elevation {elev_result['max']:.1f}m is lower than Mount Teide (3703m)")
            elif elev_result['max'] > 3720:
                elev_result['warnings'] = elev_result.get('warnings', [])
                elev_result['warnings'].append(f"Maximum elevation {elev_result['max']:.1f}m is higher than Mount Teide (3703m)")
            
            # Check for constant values
            if elev_result['min'] == elev_result['max']:
                elev_result['no_constant'] = False
                elev_result['issues'].append("Constant elevation values detected")
            
            # Check for NaN values
            if np.any(np.isnan(elev_data)):
                elev_result['no_nan'] = False
                elev_result['issues'].append("NaN values detected in elevation data")
            
            results['elevation'] = elev_result
        
        # Validate slope data
        if hasattr(self, 'slope_data'):
            slope_data = self.slope_data
            slope_result = {
                'min': float(slope_data.min()),
                'max': float(slope_data.max()),
                'mean': float(slope_data.mean()),
                'std': float(slope_data.std()),
                'valid_range': True,
                'no_constant': True,
                'no_nan': True,
                'issues': []
            }
            
            # Check range
            if not (VALIDATION_PARAMS['slope']['min_degrees'] <= slope_result['min'] <= slope_result['max'] <= VALIDATION_PARAMS['slope']['max_degrees']):
                slope_result['valid_range'] = False
                slope_result['issues'].append(f"Slope range {slope_result['min']:.1f}-{slope_result['max']:.1f}° outside expected range (0.0 to 90.0°)")
            
            # Check for constant values
            if slope_result['min'] == slope_result['max']:
                slope_result['no_constant'] = False
                slope_result['issues'].append("Constant slope values detected")
            
            # Check for NaN values
            if np.any(np.isnan(slope_data)):
                slope_result['no_nan'] = False
                slope_result['issues'].append("NaN values detected in slope data")
            
            results['slope'] = slope_result
        
        # Validate aspect data
        if hasattr(self, 'aspect_data'):
            aspect_data = self.aspect_data
            aspect_result = {
                'min': float(aspect_data.min()),
                'max': float(aspect_data.max()),
                'mean': float(aspect_data.mean()),
                'std': float(aspect_data.std()),
                'valid_range': True,
                'no_constant': True,
                'no_nan': True,
                'issues': []
            }
            
            # Check range
            if not (VALIDATION_PARAMS['aspect']['min_degrees'] <= aspect_result['min'] <= aspect_result['max'] <= VALIDATION_PARAMS['aspect']['max_degrees']):
                aspect_result['valid_range'] = False
                aspect_result['issues'].append(f"Aspect range {aspect_result['min']:.1f}-{aspect_result['max']:.1f}° outside expected range (0.0 to 360.0°)")
            
            # Check for constant values
            if aspect_result['min'] == aspect_result['max']:
                aspect_result['no_constant'] = False
                aspect_result['issues'].append("Constant aspect values detected")
            
            # Check for NaN values
            if np.any(np.isnan(aspect_data)):
                aspect_result['no_nan'] = False
                aspect_result['issues'].append("NaN values detected in aspect data")
            
            results['aspect'] = aspect_result
        
        # Validate barranco detection
        if hasattr(self, 'barranco_mask_data'):
            barranco_data = self.barranco_mask_data
            barranco_density = np.sum(barranco_data) / barranco_data.size
            
            barranco_result = {
                'total_cells': int(barranco_data.size),
                'barranco_cells': int(np.sum(barranco_data)),
                'density': float(barranco_density),
                'valid_density': True,
                'issues': []
            }
            
            # Check density
            if not (VALIDATION_PARAMS['barranco_detection']['min_density'] <= barranco_density <= VALIDATION_PARAMS['barranco_detection']['max_density']):
                barranco_result['valid_density'] = False
                barranco_result['issues'].append(f"Barranco density {barranco_density:.4f} outside expected range")
            
            results['barranco_detection'] = barranco_result
        
        # Validate depression detection
        if hasattr(self, 'depression_mask_data'):
            depression_data = self.depression_mask_data
            depression_density = np.sum(depression_data) / depression_data.size
            
            depression_result = {
                'total_cells': int(depression_data.size),
                'depression_cells': int(np.sum(depression_data)),
                'density': float(depression_density),
                'valid_density': True,
                'issues': []
            }
            
            # Check density
            if not (VALIDATION_PARAMS['depression_detection']['min_density'] <= depression_density <= VALIDATION_PARAMS['depression_detection']['max_density']):
                depression_result['valid_density'] = False
                depression_result['issues'].append(f"Depression density {depression_density:.4f} outside expected range")
            
            results['depression_detection'] = depression_result
        
        # Validate wind channeling
        if hasattr(self, 'wind_channeling_mask_data'):
            wind_data = self.wind_channeling_mask_data
            wind_density = np.sum(wind_data) / wind_data.size
            
            wind_result = {
                'total_cells': int(wind_data.size),
                'wind_channeling_cells': int(np.sum(wind_data)),
                'density': float(wind_density),
                'valid_density': True,
                'issues': []
            }
            
            # Check density
            if not (VALIDATION_PARAMS['wind_channeling']['min_density'] <= wind_density <= VALIDATION_PARAMS['wind_channeling']['max_density']):
                wind_result['valid_density'] = False
                wind_result['issues'].append(f"Wind channeling density {wind_density:.4f} outside expected range")
            
            results['wind_channeling'] = wind_result
        
        self.validation_results['data_quality'] = results
        
        # Collect issues
        for result in results.values():
            if 'issues' in result and result['issues']:
                self.validation_results['issues'].extend(result['issues'])
        
        return results
    
    def validate_spatial_consistency(self) -> Dict[str, Any]:
        """Validate spatial consistency between datasets."""
        logger.info("🗺️ Validating spatial consistency...")
        
        results = {
            'dimensions_match': True,
            'spatial_extent': {},
            'issues': []
        }
        
        # Get dimensions from elevation data (reference)
        if hasattr(self, 'elevation_data'):
            ref_shape = self.elevation_data.shape
            results['spatial_extent']['reference_shape'] = ref_shape
            results['spatial_extent']['total_cells'] = ref_shape[0] * ref_shape[1]
            
            # Check all other datasets have same dimensions
            datasets_to_check = [
                ('slope', 'slope_data'),
                ('aspect', 'aspect_data'),
                ('barranco_mask', 'barranco_mask_data'),
                ('barranco_directions', 'barranco_directions_data'),
                ('depression_mask', 'depression_mask_data'),
                ('wind_channeling_mask', 'wind_channeling_mask_data'),
                ('wind_amplification', 'wind_amplification_data'),
                ('wind_direction_modification', 'wind_direction_modification_data')
            ]
            
            for name, attr_name in datasets_to_check:
                if hasattr(self, attr_name):
                    data = getattr(self, attr_name)
                    if data.shape != ref_shape:
                        results['dimensions_match'] = False
                        results['issues'].append(f"{name} shape {data.shape} doesn't match reference {ref_shape}")
                else:
                    results['issues'].append(f"{name} data not available for dimension check")
        
        self.validation_results['spatial_consistency'] = results
        
        if results['issues']:
            self.validation_results['issues'].extend(results['issues'])
        
        return results
    
    def perform_statistical_analysis(self) -> Dict[str, Any]:
        """Perform statistical analysis of the terrain data."""
        logger.info("📈 Performing statistical analysis...")
        
        results = {}
        
        # Elevation statistics
        if hasattr(self, 'elevation_data'):
            elev_data = self.elevation_data
            results['elevation_stats'] = {
                'min': float(elev_data.min()),
                'max': float(elev_data.max()),
                'mean': float(elev_data.mean()),
                'median': float(np.median(elev_data)),
                'std': float(elev_data.std()),
                'q25': float(np.percentile(elev_data, 25)),
                'q75': float(np.percentile(elev_data, 75)),
                'iqr': float(np.percentile(elev_data, 75) - np.percentile(elev_data, 25))
            }
            
            # Validate elevation statistics for mixed sea/land DTM
            elevation_validation = {
                'median_in_range': VALIDATION_PARAMS['statistical']['elevation']['expected_median_range'][0] <= results['elevation_stats']['median'] <= VALIDATION_PARAMS['statistical']['elevation']['expected_median_range'][1],
                'mean_in_range': VALIDATION_PARAMS['statistical']['elevation']['expected_mean_range'][0] <= results['elevation_stats']['mean'] <= VALIDATION_PARAMS['statistical']['elevation']['expected_mean_range'][1],
                'std_in_range': VALIDATION_PARAMS['statistical']['elevation']['expected_std_range'][0] <= results['elevation_stats']['std'] <= VALIDATION_PARAMS['statistical']['elevation']['expected_std_range'][1]
            }
            results['elevation_validation'] = elevation_validation
            
            # Add validation messages
            if not elevation_validation['median_in_range']:
                self.validation_results['warnings'].append(f"Elevation median {results['elevation_stats']['median']:.1f}m outside expected range for mixed sea/land DTM")
            if not elevation_validation['mean_in_range']:
                self.validation_results['warnings'].append(f"Elevation mean {results['elevation_stats']['mean']:.1f}m outside expected range for mixed sea/land DTM")
        
        # Slope statistics
        if hasattr(self, 'slope_data'):
            slope_data = self.slope_data
            results['slope_stats'] = {
                'min': float(slope_data.min()),
                'max': float(slope_data.max()),
                'mean': float(slope_data.mean()),
                'median': float(np.median(slope_data)),
                'std': float(slope_data.std()),
                'q25': float(np.percentile(slope_data, 25)),
                'q75': float(np.percentile(slope_data, 75)),
                'steep_slopes_pct': float(np.sum(slope_data > 30) / slope_data.size * 100)
            }
            
            # Validate slope statistics for mixed sea/land DTM
            slope_validation = {
                'median_in_range': VALIDATION_PARAMS['statistical']['slope']['expected_median_range'][0] <= results['slope_stats']['median'] <= VALIDATION_PARAMS['statistical']['slope']['expected_median_range'][1],
                'mean_in_range': VALIDATION_PARAMS['statistical']['slope']['expected_mean_range'][0] <= results['slope_stats']['mean'] <= VALIDATION_PARAMS['statistical']['slope']['expected_mean_range'][1],
                'steep_slopes_pct_in_range': VALIDATION_PARAMS['statistical']['slope']['expected_steep_slopes_pct'][0] <= results['slope_stats']['steep_slopes_pct'] <= VALIDATION_PARAMS['statistical']['slope']['expected_steep_slopes_pct'][1]
            }
            results['slope_validation'] = slope_validation
            
            # Add validation messages
            if not slope_validation['median_in_range']:
                self.validation_results['warnings'].append(f"Slope median {results['slope_stats']['median']:.1f}° outside expected range for mixed sea/land DTM")
            if not slope_validation['steep_slopes_pct_in_range']:
                self.validation_results['warnings'].append(f"Steep slopes percentage {results['slope_stats']['steep_slopes_pct']:.1f}% outside expected range for mixed sea/land DTM")
        
        # Aspect statistics
        if hasattr(self, 'aspect_data'):
            aspect_data = self.aspect_data
            results['aspect_stats'] = {
                'min': float(aspect_data.min()),
                'max': float(aspect_data.max()),
                'mean': float(aspect_data.mean()),
                'median': float(np.median(aspect_data)),
                'std': float(aspect_data.std()),
                'q25': float(np.percentile(aspect_data, 25)),
                'q75': float(np.percentile(aspect_data, 75))
            }
        
        # Feature density analysis
        feature_densities = {}
        if hasattr(self, 'barranco_mask_data'):
            feature_densities['barranco'] = float(np.sum(self.barranco_mask_data) / self.barranco_mask_data.size)
        if hasattr(self, 'depression_mask_data'):
            feature_densities['depression'] = float(np.sum(self.depression_mask_data) / self.depression_mask_data.size)
        if hasattr(self, 'wind_channeling_mask_data'):
            feature_densities['wind_channeling'] = float(np.sum(self.wind_channeling_mask_data) / self.wind_channeling_mask_data.size)
        
        results['feature_densities'] = feature_densities
        
        # Cross-validation checks
        if hasattr(self, 'barranco_mask_data') and hasattr(self, 'slope_data'):
            # Check that barrancos are on steep slopes
            steep_slopes = self.slope_data > 25  # Using 25° threshold from updated parameters
            barranco_on_steep = np.logical_and(self.barranco_mask_data, steep_slopes)
            barranco_steep_ratio = np.sum(barranco_on_steep) / np.sum(self.barranco_mask_data) if np.sum(self.barranco_mask_data) > 0 else 0
            
            results['barranco_validation'] = {
                'barranco_on_steep_ratio': float(barranco_steep_ratio),
                'expected_min_ratio': 0.8,  # At least 80% of barrancos should be on steep slopes
                'validation_passed': barranco_steep_ratio >= 0.8
            }
            
            if barranco_steep_ratio < 0.8:
                self.validation_results['warnings'].append(f"Only {barranco_steep_ratio:.1%} of barrancos are on steep slopes (expected ≥80%)")
        
        self.validation_results['statistical_analysis'] = results
        
        return results
    
    def generate_validation_plots(self, output_dir: str = None) -> List[str]:
        """Generate validation plots for visual inspection."""
        logger.info("📊 Generating validation plots...")
        
        if output_dir is None:
            output_dir = self.preprocessed_dir / "validation_plots"
        
        output_dir = Path(output_dir)
        output_dir.mkdir(exist_ok=True)
        
        plot_files = []
        
        # Create a comprehensive validation figure
        fig, axes = plt.subplots(2, 3, figsize=(18, 12))
        fig.suptitle('Preprocessed Terrain Validation', fontsize=16, fontweight='bold')
        
        # Plot 1: Elevation histogram
        if hasattr(self, 'elevation_data'):
            axes[0, 0].hist(self.elevation_data.flatten(), bins=50, alpha=0.7, color='blue')
            axes[0, 0].set_title('Elevation Distribution')
            axes[0, 0].set_xlabel('Elevation (m)')
            axes[0, 0].set_ylabel('Frequency')
            axes[0, 0].grid(True, alpha=0.3)
        
        # Plot 2: Slope histogram
        if hasattr(self, 'slope_data'):
            axes[0, 1].hist(self.slope_data.flatten(), bins=50, alpha=0.7, color='green')
            axes[0, 1].set_title('Slope Distribution')
            axes[0, 1].set_xlabel('Slope (°)')
            axes[0, 1].set_ylabel('Frequency')
            axes[0, 1].grid(True, alpha=0.3)
        
        # Plot 3: Aspect histogram
        if hasattr(self, 'aspect_data'):
            axes[0, 2].hist(self.aspect_data.flatten(), bins=36, alpha=0.7, color='red')
            axes[0, 2].set_title('Aspect Distribution')
            axes[0, 2].set_xlabel('Aspect (°)')
            axes[0, 2].set_ylabel('Frequency')
            axes[0, 2].grid(True, alpha=0.3)
        
        # Plot 4: Barranco detection
        if hasattr(self, 'barranco_mask_data'):
            axes[1, 0].imshow(self.barranco_mask_data, cmap='Reds', alpha=0.8)
            axes[1, 0].set_title(f'Barranco Detection\n({np.sum(self.barranco_mask_data):,} cells, {np.sum(self.barranco_mask_data)/self.barranco_mask_data.size:.2%})')
            axes[1, 0].axis('off')
        
        # Plot 5: Depression detection
        if hasattr(self, 'depression_mask_data'):
            axes[1, 1].imshow(self.depression_mask_data, cmap='Blues', alpha=0.8)
            axes[1, 1].set_title(f'Depression Detection\n({np.sum(self.depression_mask_data):,} cells, {np.sum(self.depression_mask_data)/self.depression_mask_data.size:.2%})')
            axes[1, 1].axis('off')
        
        # Plot 6: Wind channeling
        if hasattr(self, 'wind_channeling_mask_data'):
            axes[1, 2].imshow(self.wind_channeling_mask_data, cmap='YlOrRd', alpha=0.8)
            axes[1, 2].set_title(f'Wind Channeling\n({np.sum(self.wind_channeling_mask_data):,} cells, {np.sum(self.wind_channeling_mask_data)/self.wind_channeling_mask_data.size:.2%})')
            axes[1, 2].axis('off')
        
        plt.tight_layout()
        plot_path = output_dir / "terrain_validation_overview.png"
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')
        plt.close()
        plot_files.append(str(plot_path))
        
        # Create feature density comparison
        if any(hasattr(self, f'{name}_data') for name in ['barranco_mask', 'depression_mask', 'wind_channeling_mask']):
            fig, ax = plt.subplots(figsize=(10, 6))
            
            features = []
            densities = []
            
            if hasattr(self, 'barranco_mask_data'):
                features.append('Barrancos')
                densities.append(np.sum(self.barranco_mask_data) / self.barranco_mask_data.size)
            
            if hasattr(self, 'depression_mask_data'):
                features.append('Depressions')
                densities.append(np.sum(self.depression_mask_data) / self.depression_mask_data.size)
            
            if hasattr(self, 'wind_channeling_mask_data'):
                features.append('Wind Channeling')
                densities.append(np.sum(self.wind_channeling_mask_data) / self.wind_channeling_mask_data.size)
            
            bars = ax.bar(features, densities, color=['red', 'blue', 'orange'], alpha=0.7)
            ax.set_title('Terrain Feature Densities')
            ax.set_ylabel('Density (fraction of total cells)')
            ax.set_ylim(0, max(densities) * 1.2)
            
            # Add value labels on bars
            for bar, density in zip(bars, densities):
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + height*0.01,
                       f'{density:.4f}', ha='center', va='bottom')
            
            plt.tight_layout()
            plot_path = output_dir / "feature_densities.png"
            plt.savefig(plot_path, dpi=300, bbox_inches='tight')
            plt.close()
            plot_files.append(str(plot_path))
        
        return plot_files
    
    def run_full_validation(self, generate_plots: bool = True) -> Dict[str, Any]:
        """Run the complete validation suite."""
        logger.info("🚀 Starting comprehensive terrain validation...")
        
        try:
            # Run all validation steps
            self.validate_file_integrity()
            self.validate_data_quality()
            self.validate_spatial_consistency()
            self.perform_statistical_analysis()
            
            # Generate plots if requested
            plot_files = []
            if generate_plots:
                plot_files = self.generate_validation_plots()
            
            # Determine overall status
            if self.validation_results['issues']:
                self.validation_results['overall_status'] = 'FAILED'
            elif self.validation_results['warnings']:
                self.validation_results['overall_status'] = 'PASSED_WITH_WARNINGS'
            else:
                self.validation_results['overall_status'] = 'PASSED'
            
            # Add plot files to results
            self.validation_results['plot_files'] = plot_files
            
            logger.info(f"✅ Validation completed with status: {self.validation_results['overall_status']}")
            
        except Exception as e:
            logger.error(f"❌ Validation failed with error: {e}")
            self.validation_results['overall_status'] = 'ERROR'
            self.validation_results['issues'].append(f"Validation error: {e}")
        
        return self.validation_results
    
    def print_summary(self):
        """Print a comprehensive validation summary."""
        print("\n" + "="*80)
        print("🏔️ PREPROCESSED TERRAIN VALIDATION SUMMARY")
        print("="*80)
        
        # Overall status
        status = self.validation_results['overall_status']
        status_emoji = "✅" if status == "PASSED" else "⚠️" if status == "PASSED_WITH_WARNINGS" else "❌"
        print(f"\n{status_emoji} Overall Status: {status}")
        
        # File integrity summary
        print(f"\n📁 File Integrity:")
        file_results = self.validation_results['file_integrity']
        for filename, result in file_results.items():
            status = "✅" if result['exists'] and result['readable'] else "❌"
            size_str = f"({result['size_mb']:.1f} MB)" if result['size_mb'] > 0 else ""
            print(f"   {status} {filename} {size_str}")
        
        # Data quality summary
        print(f"\n📊 Data Quality:")
        quality_results = self.validation_results['data_quality']
        for dataset, result in quality_results.items():
            if 'issues' in result and result['issues']:
                print(f"   ❌ {dataset}: {len(result['issues'])} issues")
                for issue in result['issues'][:2]:  # Show first 2 issues
                    print(f"      - {issue}")
            else:
                print(f"   ✅ {dataset}: Valid")
        
        # Statistical summary
        print(f"\n📈 Statistical Summary:")
        stats = self.validation_results['statistical_analysis']
        if 'elevation_stats' in stats:
            elev = stats['elevation_stats']
            print(f"   🏔️ Elevation: {elev['min']:.0f}-{elev['max']:.0f}m (mean: {elev['mean']:.0f}m)")
        
        if 'slope_stats' in stats:
            slope = stats['slope_stats']
            print(f"   📐 Slope: {slope['min']:.1f}-{slope['max']:.1f}° (mean: {slope['mean']:.1f}°)")
            print(f"   📐 Steep slopes (>30°): {slope['steep_slopes_pct']:.1f}%")
        
        if 'feature_densities' in stats:
            densities = stats['feature_densities']
            for feature, density in densities.items():
                print(f"   🎯 {feature.title()}: {density:.4f} ({density*100:.2f}%)")
        
        # Issues and warnings
        if self.validation_results['issues']:
            print(f"\n❌ Issues Found ({len(self.validation_results['issues'])}):")
            for issue in self.validation_results['issues'][:5]:  # Show first 5 issues
                print(f"   - {issue}")
            if len(self.validation_results['issues']) > 5:
                print(f"   ... and {len(self.validation_results['issues']) - 5} more issues")
        
        if self.validation_results['warnings']:
            print(f"\n⚠️ Warnings ({len(self.validation_results['warnings'])}):")
            for warning in self.validation_results['warnings'][:3]:  # Show first 3 warnings
                print(f"   - {warning}")
            if len(self.validation_results['warnings']) > 3:
                print(f"   ... and {len(self.validation_results['warnings']) - 3} more warnings")
        
        # Plot files
        if 'plot_files' in self.validation_results and self.validation_results['plot_files']:
            print(f"\n📊 Validation plots generated:")
            for plot_file in self.validation_results['plot_files']:
                print(f"   - {plot_file}")
        
        print("\n" + "="*80)
    
    def save_validation_report(self, output_file: str = None) -> str:
        """Save validation results to a JSON file."""
        if output_file is None:
            output_file = self.preprocessed_dir / "validation_report.json"
        
        # Convert numpy types to native Python types for JSON serialization
        def convert_numpy_types(obj):
            if isinstance(obj, np.integer):
                return int(obj)
            elif isinstance(obj, np.floating):
                return float(obj)
            elif isinstance(obj, np.ndarray):
                return obj.tolist()
            elif isinstance(obj, dict):
                return {str(key): convert_numpy_types(value) for key, value in obj.items()}
            elif isinstance(obj, list):
                return [convert_numpy_types(item) for item in obj]
            elif isinstance(obj, bool):
                return bool(obj)
            elif isinstance(obj, np.bool_):
                return bool(obj)
            else:
                return str(obj) if hasattr(obj, '__class__') else obj
        
        report_data = convert_numpy_types(self.validation_results)
        
        with open(output_file, 'w') as f:
            json.dump(report_data, f, indent=2)
        
        logger.info(f"📄 Validation report saved to: {output_file}")
        return str(output_file)


def main():
    """Main function to run terrain validation."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Validate preprocessed terrain outputs")
    parser.add_argument("preprocessed_dir", help="Path to preprocessed terrain directory")
    parser.add_argument("--no-plots", action="store_true", help="Skip plot generation")
    parser.add_argument("--output-report", help="Path for validation report JSON file")
    
    args = parser.parse_args()
    
    # Validate input directory
    if not os.path.exists(args.preprocessed_dir):
        print(f"❌ Error: Preprocessed directory not found: {args.preprocessed_dir}")
        sys.exit(1)
    
    # Run validation
    validator = PreprocessedTerrainValidator(args.preprocessed_dir)
    results = validator.run_full_validation(generate_plots=not args.no_plots)
    
    # Print summary
    validator.print_summary()
    
    # Save report
    if args.output_report:
        report_file = validator.save_validation_report(args.output_report)
    else:
        report_file = validator.save_validation_report()
    
    # Exit with appropriate code
    if results['overall_status'] == 'PASSED':
        print("🎉 Validation PASSED - Terrain preprocessing looks good!")
        sys.exit(0)
    elif results['overall_status'] == 'PASSED_WITH_WARNINGS':
        print("⚠️ Validation PASSED with warnings - Check the warnings above")
        sys.exit(0)
    else:
        print("❌ Validation FAILED - Check the issues above")
        sys.exit(1)


if __name__ == "__main__":
    main() 